language: node_js
node_js:
  - '10'
  - '9'
  - '8'
install:
  - travis_retry npm install
  - npm i -g codecov
script:
  - npm run test

after_success:
  - npm run coverage
  - codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
